# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

icons = [
    ["","","0000.png","symbols"],
    ["","Aktivitet","0001.png","symbols"],
    ["","Transport","0002.png","symbols"],
    ["","Transport","0003.png","symbols"],
    ["","Transport","0004.png","symbols"],
    ["","Transport","0005.png","symbols"],
    ["","Transport","0006.png","symbols"],
    ["","Aktivitet","0007.png","symbols"],
    ["","Aktivitet","0008.png","symbols"],
    ["","Aktivitet","0009.png","symbols"],
    ["","Aktivitet","0010.png","symbols"],
    ["","Verktyg","0011.png","symbols"],
    ["","Verktyg","0012.png","symbols"],
    ["","Verktyg","0013.png","symbols"],
    ["","Boende","0014.png","symbols"],
    ["","Resurs","0016.png","symbols"],
    ["","Resurs","0017.png","symbols"],
    ["","Verktyg","0018.png","symbols"],
    ["","Sport","0019.png","symbols"],
    ["","Sport","0020.png","symbols"],
    ["","Transport","0021.png","symbols"],
    ["","Transport","0022.png","symbols"],
    ["","Transport","0023.png","symbols"],
    ["","Transport","0024.png","symbols"],
    ["","Transport","0025.png","symbols"],
    ["","Sport","0026.png","symbols"],
    ["","Sport","0027.png","symbols"],
    ["","Boende","0028.png","symbols"],
    ["","Aktivitet","0029.png","symbols"],
    ["","Aktivitet","0030.png","symbols"],
    ["","Aktivitet","0031.png","symbols"],
    ["","Transport","0032.png","symbols"],
    ["","Sport","0033.png","symbols"],
    ["","Boende","0034.png","symbols"],
    ["","Boende","0035.png","symbols"],
    ["","Aktivitet","0036.png","symbols"],
    ["","Aktivitet","0037.png","symbols"],
    ["","Verktyg","0038.png","symbols"],
    ["","Sport","0039.png","symbols"],
    ["","Sport","0040.png","symbols"],
    ["","Sport","0041.png","symbols"],
    ["","Sport","0042.png","symbols"],
    ["","Aktivitet","0043.png","symbols"],
    ["","Verktyg","0044.png","symbols"],
    ["","Verktyg","0045.png","symbols"],
    ["","Verktyg","0046.png","symbols"],
    ["","Aktivitet","0047.png","symbols"],
    ["","Verktyg","0048.png","symbols"],
    ["","Transport","0049.png","symbols"],
    ["","Aktivitet","0050.png","symbols"],
    ["","Transport","0051.png","symbols"],
    ["","Transport","0052.png","symbols"],
    ["","Transport","0053.png","symbols"],
    ["","Transport","0054.png","symbols"],
    ["","Transport","0055.png","symbols"],
    ["","Transport","0056.png","symbols"],
    ["","Transport","0057.png","symbols"],
    ["","Transport","0058.png","symbols"],
    ["","Transport","0059.png","symbols"],
    ["","Transport","0060.png","symbols"],
    ["","Transport","0061.png","symbols"],
    ["","Boende","0063.png","symbols"],
    ["","Transport","0064.png","symbols"],
    ["","Transport","0065.png","symbols"],
    ["","Transport","0066.png","symbols"],
    ["","Aktivitet","0067.png","symbols"],
    ["","Boende","0068.png","symbols"],
    ["","Boende","0069.png","symbols"],
    ["","Resurs","0070.png","symbols"],
    ["","Resurs","0071.png","symbols"],
    ["","Resurs","0072.png","symbols"],
    ["","Resurs","0073.png","symbols"],
    ["","Resurs","0074.png","symbols"],
    ["","Resurs","0075.png","symbols"],
    ["","Transport","0076.png","symbols"],
    ["","Boende","0077.png","symbols"],
    ["","Sport","0078.png","symbols"],
    ["","Transport","0079.png","symbols"],
    ["","Transport","0080.png","symbols"],
    ["Snow","","snow.png","patterns"],
    ["Grey Floral","","greyfloral.png","patterns"],
    ["Linen","","linen.png","patterns"],
    ["Chruch","","chruch.png","patterns"],
    ["Farmer","","farmer.png","patterns"],
    ["Foggy Birds","","foggy_birds.png","patterns"],
    ["Handmade Paper","","handmadepaper.png","patterns"],
    ["Ice Age","","ice_age.png","patterns"],
    ["Purty Wood","","purty_wood.png","patterns"],
    ["Lined Paper","","lined_paper.png","patterns"],
    ["Leather 1","","leather_1.png","patterns"],
    ["Retro Intro","","retro_intro.png","patterns"],
    ["Subtle","","subtle.png","patterns"],
    ["Vichy","","vichy.png","patterns"],
    ["Diamond Upholstery","","diamond_upholstery.png","patterns"],
    ["Gradient Squares","","gradient_squares.png","patterns"],
    ["Pool Table","","pool_table.png","patterns"],
    ["","Sport","0085.png","symbols"],
    ["","Sport","0084.png","symbols"],
    ["","Sport","0083.png","symbols"],
    ["","Verktyg","0082.png","symbols"],
    ["","Verktyg","0086.png","symbols"],
    ["","Verktyg","0081.png","symbols"],
    ["","Verktyg","0087.png","symbols"],
    ["","Verktyg","0088.png","symbols"],
    ["","Verktyg","0089.png","symbols"],
    ["","Verktyg","0090.png","symbols"],
    ["","Verktyg","0091.png","symbols"],
    ["","Verktyg","0092.png","symbols"],
    ["","Verktyg","0093.png","symbols"],
    ["","Verktyg","0094.png","symbols"],
    ["","Verktyg","0095.png","symbols"],
    ["","Verktyg","0096.png","symbols"],
    ["","Aktivitet","0097.png","symbols"],
    ["","Sport","0098.png","symbols"],
    ["","Sport","0099.png","symbols"],
    ["","Sport","0100.png","symbols"],
    ["","Aktivitet","0101.png","symbols"],
    ["","Sport","0102.png","symbols"],
    ["","Sport","0103.png","symbols"],
    ["","Aktivitet","0104.png","symbols"],
    ["","Aktivitet","0105.png","symbols"],
    ["","Boende","0106.png","symbols"],
    ["","Boende","0107.png","symbols"],
    ["","Boende","0108.png","symbols"],
    ["","Transport","0109.png","symbols"],
    ["","Sport","0111.png","symbols"],
    ["","Aktivitet","0112.png","symbols"],
    ["","Sport","0113.png","symbols"],
    ["","Sport","0114.png","symbols"],
    ["","Sport","0115.png","symbols"],
    ["","Sport","0116.png","symbols"],
    ["","Sport","0117.png","symbols"],
    ["","Sport","0118.png","symbols"],
    ["","Sport","0119.png","symbols"],
    ["","Sport","0120.png","symbols"],
    ["","Sport","0121.png","symbols"],
    ["","Resurs","0122.png","symbols"],
    ["","Resurs","0123.png","symbols"],
    ["","Resurs","0124.png","symbols"],
    ["","Resurs","0125.png","symbols"],
    ["","Resurs","0126.png","symbols"],
    ["","Resurs","0127.png","symbols"],
    ["","Resurs","0128.png","symbols"],
    ["","Aktivitet","0129.png","symbols"],
    ["","Aktivitet","0130.png","symbols"],
    ["","Aktivitet","0131.png","symbols"],
    ["","Resurs","0132.png","symbols"],
    ["","Boende","0133.png","symbols"]
]

Icon.delete_all
icons.each do |icon|
  name, tags, image, folder = icon
  Icon.create([:image => image, :name => name, :tags => tags, :folder => folder ])
end
